### ISSUE TITLE
$LEGO_CERT_KEY_PATH not defined, certificates don't exist with underscore prefix

### ISSUE THREAD

**Issue by ilium007** [foorschtbar/routeros-letsencrypt-docker#2]
This check never fails because $LEGO_CERT_KEY_PATH is never previously defined:

```
if [ ! -f $CERTIFICATE ] && [ ! -f $LEGO_CERT_KEY_PATH ]; then
    echo "File(s) not found:\n$CERTIFICATE\n$KEY\n" && exit 1
fi
```

It should fail because the certificate and key files do not exist on disk with the "_." prefix.

```
CERTIFICATE="/letsencrypt/certificates/_.$ROUTEROS_DOMAIN.pem"
KEY="/letsencrypt/certificates/_.$ROUTEROS_DOMAIN.key"
```

<img width="549" alt="image" src="https://user-images.githubusercontent.com/732766/136716652-528b0352-9fe0-4592-b707-8b2a697e2c92.png">

Docker compose file:

```
version: "3"

services:
  app:
    image: foorschtbar/routeros-letsencrypt
    environment:
      - LEGO_STAGING=1 # 0 for production, 1 for staging
      - LEGO_PROVIDER=digitalocean
      - LEGO_DOMAINS=router01.xxx.xxx.dev
      - LEGO_EMAIL_ADDRESS=xxx@xxx.dev
      - LEGO_KEY_TYPE
      - LEGO_ARGS=--dns.disable-cp
      - DO_AUTH_TOKEN=xxx
      - ROUTEROS_USER=letsencrypt
      - ROUTEROS_HOST=xxx
      - ROUTEROS_SSH_PORT=22
      - ROUTEROS_PRIVATE_KEY=/id_rsa/.id_rsa
      - ROUTEROS_DOMAIN=router01.xxx.xxx.dev
    volumes:
      - ./data:/letsencrypt # To store persistent authorization information between container restarts
      - .ssh:/id_rsa
    restart: unless-stopped
```
